apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-guestbook
spec:
  project: kargo-poc
  source:
    repoURL: https://github.com/dhpup/bkargo.git
    path: kargo
  destination:
    #server: https://b5bxdj947v9xturb-cplane.kargosvcs.akuity.cloud
    name: kargo-poc
    #namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
